### ISSUE TITLE
email activation link not received in the gmail

### ISSUE THREAD

**Issue by employee1akthar** [egorsmkv/simple-django-login-and-register#104]
i had installed django , when  i ![email issue](https://user-images.githubusercontent.com/121218874/209077974-5897e5d7-893c-4f7b-b5c6-ed5ff2afaaf3.png) run a project but i had an issue in activation mail link not received in the gmail account .....what can i do for it...

**Comment by egorsmkv** [comment]
You need to configure SMTP credentials in the `settings.py` file

**Comment by employee1akthar** [comment]
how to configure settings.py ....also provide some screenshots...

**Comment by egorsmkv** [comment]
https://github.com/egorsmkv/simple-django-login-and-register/blob/master/source/app/conf/production/settings.py#L68
