### ISSUE TITLE
How can I merge this with an existing Django project? I can't separate the file structure into an app directory.我该怎么把它与已有Django项目合并？这些代码的文件结构我无法分离出app目录

### ISSUE THREAD

**Issue by xufuyu** [egorsmkv/simple-django-login-and-register#113]
How can I merge this with an existing Django project? I can't separate the file structure into an app directory.

**Comment by egorsmkv** [comment]
You need to have Django knowledge to make it. There is no specific advice to your question, you just copy files from the repo to your project and that's all.
