### ISSUE TITLE
Activation email not coming

### ISSUE THREAD

**Issue by VishwaParmar** [egorsmkv/simple-django-login-and-register#122]
I cloned this project in Linux, It started running but after registration, there was no activation code sent. I tried  with 3-4 emails still not getting any activation code as well.

**Comment by VishwaParmar** [comment]
I am trying to run on AWS ec2 with Linux, I want to check if it's fully running or not. Where should I can for Smtp connection

**Comment by egorsmkv** [comment]
Here - https://github.com/egorsmkv/simple-django-login-and-register/blob/master/source/app/conf/production/settings.py#L66

**Comment by VishwaParmar** [comment]
Okk so i will change my email over there for sending emails right

**Comment by VishwaParmar** [comment]
Also, will do the changes in EMAIL_HOST = ''
EMAIL_HOST_USER = ''
DEFAULT_FROM_EMAIL = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

**Comment by egorsmkv** [comment]
Yes, it is the solution to your problem.
