### ISSUE TITLE
class Activation does not have a 'DoesNotExist' member

### ISSUE THREAD

**Issue by karanrajpal14** [egorsmkv/simple-django-login-and-register#32]
Is this intended? If I'm not wrong, the Activation class has no such member. Does that need to be added in?

https://github.com/egorsmkv/simple-django-login-and-register/blob/fe2ddeb7a2215b1a443877cf1648add675a9f31d/source/accounts/forms.py#L225

https://github.com/egorsmkv/simple-django-login-and-register/blob/fe2ddeb7a2215b1a443877cf1648add675a9f31d/source/accounts/models.py#L7

**Comment by egorsmkv** [comment]
It is not just python code, it is a Django project. Django raises an exception like this when an object was not found.

**Comment by egorsmkv** [comment]
See the documentation here https://docs.djangoproject.com/en/2.0/ref/models/instances/#django.db.models.Model.DoesNotExist

**Comment by karanrajpal14** [comment]
My apologies. Should've confirmed this myself first. Thank you for pointing it out!
