### ISSUE TITLE
MultipleObjectsReturned on ResendActivation

### ISSUE THREAD

**Issue by karanrajpal14** [egorsmkv/simple-django-login-and-register#33]
Since you are using either username or email to log in, and no unique constraint is set, there are possibilities of having multiple users with the same credentials.

https://github.com/egorsmkv/simple-django-login-and-register/blob/fe2ddeb7a2215b1a443877cf1648add675a9f31d/source/accounts/forms.py#L167

In my case, first I registered through the website which created a normal user. I then needed a superuser to check if everything was working as intended and I used the same email for both. But, once the accounts were created, if I use my email as an input, this error is thrown since get() only works if the QuerySet has one object but I had two. I think you might need to account for such a case as well. Thank you!

**Comment by egorsmkv** [comment]
Okay. I will see this situation in details later.

**Comment by karanrajpal14** [comment]
Just returning the first one is a bad idea, don't you think?

With this approach, I'll never be able to reset my second account at all knowing just my email.
You should try to do something similar to what Reddit does. If I have two accounts registered to the same email, it sends a password reset email for both accounts.

That would ensure that the user who can't remember his username isn't left out. What do you think @egorsmkv?

**Comment by egorsmkv** [comment]
Now, if you create an account by the webapp, not by Django's CLI, you can't to create two accounts with the same email. The email is a unique field.

See this code:
https://github.com/egorsmkv/simple-django-login-and-register/blob/master/source/accounts/forms.py#L134

**Comment by Prinno** [comment]
I try to add smtp into setting production but the app does not send the email into my Email but the email is created into the foodel tmp and not sending to the email , please help

**Comment by egorsmkv** [comment]
> I try to add smtp into setting production but the app does not send the email into my Email but the email is created into the foodel tmp and not sending to the email , please help

I suppose you didn’t disable the debug mode

**Comment by Prinno** [comment]
I put debug = false
 but I don't work and I change the debug to
Debug = os.environ.get("Debug" , false) but still it does not work

**Comment by egorsmkv** [comment]
You must change this env variable - https://github.com/egorsmkv/simple-django-login-and-register/blob/master/source/app/settings.py#L3

**Comment by Prinno** [comment]
Please if is possible can you help me the full project for this in to help
me to understand
