### ISSUE TITLE
User enumeration vulnerability

### ISSUE THREAD

**Issue by ViktorBarzin** [egorsmkv/simple-django-login-and-register#58]
Hello,

Firstly, good job on this sample project - it is really useful!

While tinkering with it, I noticed that there are multiple places where [user enumeration](https://blog.rapid7.com/2017/06/15/about-user-enumeration/) is possible.

The first, and most obvious, place is the Login form. When entering a non-existent email we get a "Invalid email address" error. When entering a valid (both activated and not activated) email but with wrong password the error is "Invalid password".

The second place where I discovered user enumeration is the "Restore password" form. Once again, the messages we get for registered and non-registered users are different. The correct behaviour is occurring when a valid email address is submitted - a message saying that if the email is correct, an email will be received. This should be the response regardless of the validity of the email address.

The next form where user enumeration was discovered is the "Remind a username" form - same issue. The response should be similar to the one described above.

The "Resend an activation code" form also suffers from user enumeration.

When registering a new account, one can also determine whether a username and/or email address is registered. This is a bit difficult to handle since we need to tell the user whether or not they can use the given username. Therefore I would leave that as is and implement some sort of CAPTCHA to avoid spammers.

I know this is just a demo project, but given that it is the first that appears when people search for django register/login, I reckon it should be rather safe. 

Depending on whether I have some free time, I may or may not submit a pull request to fix these issues. I suggest you make the changes since you know your code better. It employs quite some good coding practices so I reckon you would do a better job in changing the code where needed that I will.

Have a nice day :)

**Comment by egorsmkv** [comment]
Hello, Viktor. Thanks for the detailed message. I will become acquainted with it in a few days.

**Comment by egorsmkv** [comment]
Hello again.

I have read the article about user enumeration. I agree that it is a security issue for production-ready applications. In the first versions of the project I made the same messages for invalid credentials but changed them to visibility of a state after entering data.

The author in the second part of the article says that an attacker can use a method of time-checking for its attack on a form. It can be solved by using a message queue or a captcha.

I can integrate this package https://github.com/kbytesys/django-recaptcha2 into the project and use it on the sign up/forgot password pages. It looks good and the maintainer is updating the project.
