### ISSUE TITLE
activation code is not sending though email

### ISSUE THREAD

**Issue by RajHarry** [egorsmkv/simple-django-login-and-register#60]
Hello there...
Nice Project....

when a new user is trying to register,it is saying that **activation code is send to email**.
But that code is not recieved by that user.

if you give me the process for that.
it will be usefull..

thanks in advance......

**Comment by egorsmkv** [comment]
The project has two types of configuration: production and development. Here are their folders: https://github.com/egorsmkv/simple-django-login-and-register/tree/master/source/app/conf

Each folder has the setting.py file, inside it exist configuration variables which start with EMAIL_* prefix.

The development configuration saves all sent emails into the folder.
The production configuration uses an SMTP server to sent emails.

Read the documentation here: https://docs.djangoproject.com/en/2.1/topics/email/#email-backends
