### ISSUE TITLE
error SyntaxError: invalid escape sequence \s

### ISSUE THREAD

**Issue by osama188** [egorsmkv/simple-django-login-and-register#63]
`

Request Method: | GET
-- | --
http://127.0.0.1:8000/accounts/log-in/
2.2.4
SyntaxError
invalid escape sequence \s (element.py, line 15)
C:\Users\osama\AppData\Local\Continuum\Anaconda3\lib\site-packages\bs4\builder\__init__.py in <module>, line 7
C:\Users\osama\AppData\Local\Continuum\Anaconda3\python.exe
3.6.8
['H:\\coding\\python\\Projects\\simple-django-login-and-register\\source',  'C:\\Users\\osama\\AppData\\Local\\Continuum\\Anaconda3\\python36.zip',  'C:\\Users\\osama\\AppData\\Local\\Continuum\\Anaconda3\\DLLs',  'C:\\Users\\osama\\AppData\\Local\\Continuum\\Anaconda3\\lib',  'C:\\Users\\osama\\AppData\\Local\\Continuum\\Anaconda3',  'C:\\Users\\osama\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages',  'C:\\Users\\osama\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\Sphinx-1.5.6-py3.6.egg',  'C:\\Users\\osama\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\win32',  'C:\\Users\\osama\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\win32\\lib',  'C:\\Users\\osama\\AppData\\Local\\Continuum\\Anaconda3\\lib\\site-packages\\Pythonwin']
Tue, 8 Oct 2019 03:31:57 +0000

`
what might be the problem ?

**Comment by egorsmkv** [comment]
It is not a problem with the project. It seems to be the problem with installed packages.
