### ISSUE TITLE
I can't get email for activation

### ISSUE THREAD

**Issue by softdev9** [egorsmkv/simple-django-login-and-register#66]
- when try sign up with gmail, I didn't get email.
what's missing from source code?

**Comment by egorsmkv** [comment]
Did you configure SMTP connection that sends emails?

**Comment by softdev9** [comment]
Sorry, can you recommend any document or link for configuring SMTP connection?

**Comment by egorsmkv** [comment]
It's an example of config: https://github.com/egorsmkv/simple-django-login-and-register/blob/master/source/app/conf/production/settings.py#L68

**Comment by egorsmkv** [comment]
Also, this is the official documentation on the topic: https://docs.djangoproject.com/en/2.2/topics/email/

**Comment by softdev9** [comment]
> It's an example of config: https://github.com/egorsmkv/simple-django-login-and-register/blob/master/source/app/conf/production/settings.py#L68

I am going to send email on develop version.
