### ISSUE TITLE
not working with email 

### ISSUE THREAD

**Issue by shubh1226** [egorsmkv/simple-django-login-and-register#68]
not working with email

**Comment by egorsmkv** [comment]
Please, describe your case more detailed

**Comment by shubh1226** [comment]
Actually everything is working fine ,but I am unable to send and receive emails with link, 
I have changed the settings but still it's not working

**Comment by egorsmkv** [comment]
Did you configure SMTP credentials in the settings.py?

**Comment by shubh1226** [comment]
EMAIL_HOST_USER = 'test@example.com'
DEFAULT_FROM_EMAIL = 'test@example.com'

EMAIL_HOST = ''
EMAIL_HOST_USER = ''
DEFAULT_FROM_EMAIL = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
Changed all this settings

**Comment by egorsmkv** [comment]
You must fill them all with real credentials.

**Comment by shubh1226** [comment]
Yaa I have filled them .

**Comment by egorsmkv** [comment]
What do logs say? Any errors?

**Comment by shubh1226** [comment]
Logs didn't showed error it is working fine ,just in email settings something might be problem.

**Comment by egorsmkv** [comment]
Then it's a problem with configuration I guess, not with the project.
