### ISSUE TITLE
Custom Usage

### ISSUE THREAD

**Issue by sohamb03** [egorsmkv/simple-django-login-and-register#70]
Hello,

Please tell me a few things. I actually wanted to use your application, but to integrate it with my application, I need a few things changed, and I'm not being able to do so. Could you please guide me?

Actually what I basically want is that the `First Name` and `Last Name` is removed. I only want a username, email and password. Please tell me which portion of the code do I need to remove. Also, I do not want the `Remind Username` feature. 

As I'm new to Django, it'd be great if someone could help me sort out my problems. 

Regards,
S Bhattacharyya.

**Comment by egorsmkv** [comment]
Hello.

You already sent me two emails to my inbox. I have replied to them that it's out of my support scope for the project.

Improve your skills in Django by yourself.
