### ISSUE TITLE
BASE_DIR path in Django 3.0.1

### ISSUE THREAD

**Issue by Jannickla** [egorsmkv/simple-django-login-and-register#74]
In Django 3.0.1 CONTENT_DIR errors with missing template.

SOLUTION: Change BASE_DIR path to: BASE_DIR = os.path.dirname(os.path.dirname(__file__))

**Comment by egorsmkv** [comment]
I have not tested the code with Django 3. Any other errors?

**Comment by egorsmkv** [comment]
No answer.
