### ISSUE TITLE
Confirmation link Email not delivered after SMTP configuration set

### ISSUE THREAD

**Issue by vik2595** [egorsmkv/simple-django-login-and-register#75]
Hi Dev Team,

I've changed the required setting in source/app/conf/development/settings.py
and also SMTP settings in source/app/conf/production/settings.py .

I can't get any emails, when i try to register with my other email address. I can activate that user by following link in source/content/tmp/emails . 

But i don't get any email on my real email address. 

Following is error log

Exception happened during processing of request from ('127.0.0.1', 50679)
Traceback (most recent call last):
  File "c:\users\vik25\appdata\local\programs\python\python37\lib\socketserver.py", line 650, in process_request_
thread
    self.finish_request(request, client_address)
  File "c:\users\vik25\appdata\local\programs\python\python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\vik25\appdata\local\programs\python\python37\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\vik25\.virtualenvs\loginandregister-49NrGCkj\lib\site-packages\django\core\servers\basehttp.py",
 line 171, in handle
    self.handle_one_request()
  File "C:\Users\vik25\.virtualenvs\loginandregister-49NrGCkj\lib\site-packages\django\core\servers\basehttp.py",
(loginandregister) C:\Users\vik25\PycharmProjects\CourseCrib\login>python -V
Python 3.7.4

Please help me out. Thank you.

**Comment by egorsmkv** [comment]
Hello. Please, provide all your email config variables and be sure that the SMTP server is reachable.

**Comment by vik2595** [comment]
Hi @egorsmkv ,

Thank you for quick response,

Here are my config in production/settings.py,

ALLOWED_HOSTS = [
    '*',
]  #This is not the secure way, but i tried this for testing.

WSGI_APPLICATION = 'app.wsgi.application'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = '******@gmail.com'
DEFAULT_FROM_EMAIL = '*******@gmail.com'
EMAIL_HOST_PASSWORD = '*****'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

For dev/settings.py

ALLOWED_HOSTS = ['*']  

WSGI_APPLICATION = 'app.wsgi.application'

EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = os.path.join(CONTENT_DIR, 'tmp/emails')
EMAIL_HOST_USER = '*****@gmail.com'
DEFAULT_FROM_EMAIL = '*****@gmail.com'

**Comment by egorsmkv** [comment]
It misconfiguration on your side because you are using Google to send emails and Google has restrictions in this.

**Comment by sssplCodeStar** [comment]
> It misconfiguration on your side because you are using Google to send emails and Google has restrictions in this.

then which mail want to use..??

**Comment by samannazz** [comment]
vik2595 have your problem resolved?? actually i get the same problem.
