### ISSUE TITLE
Confirmation Email is not Wroking!?

### ISSUE THREAD

**Issue by samannazz** [egorsmkv/simple-django-login-and-register#85]
I have run this project as it is, but do some required changes in production/settings.py and development/settings.py 

production/settings.py:
```
WSGI_APPLICATION = 'app.wsgi.application'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'app797644@gmail.com'
DEFAULT_FROM_EMAIL = 'app797644@gmail.com'
EMAIL_HOST_PASSWORD = '12345678'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
```
I have tried other EMAIL_HOST than gmail and it still shows error.

development/settings.py
```
`WSGI_APPLICATION = 'app.wsgi.application'
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = os.path.join(CONTENT_DIR, 'tmp/emails')
EMAIL_HOST_USER = 'app797644@gmail.com'
DEFAULT_FROM_EMAIL = 'app797644@gmail.com
```
To test the whole process i just make simple process of signin, signout and signup with google host seperately and it works fine. but I don't know whats the hack with this project it shows nothing whatever solutions i have tried.

**Comment by egorsmkv** [comment]
GMail restricts sending mail form personal accounts by default. You need to configure the account previously. 

Check these articles out:

- https://kb.synology.com/en-global/SRM/tutorial/How_to_use_Gmail_SMTP_server_to_send_emails_for_SRM
- https://kinsta.com/blog/gmail-smtp-server/

**Comment by samannazz** [comment]
> To test the whole process i just make simple process of signin, signout and signup with google host seperately and it works fine.

As i have mentioned earlier that i have used the same google account app797644@gmail.com for email confirmation in another project. and its working fine there. Like 

![image](https://user-images.githubusercontent.com/89451747/145754380-3a8f29be-851e-4f73-a2dd-e1f7fa5775f0.png)  
![image](https://user-images.githubusercontent.com/89451747/145754457-3661282e-d702-4b3a-9dbd-98ac2b55ea28.png)
I have make these simple form and use this below setting:  

![image](https://user-images.githubusercontent.com/89451747/145754547-268b4308-6f83-40a0-b670-3e633e5341eb.png)  
And enabled **LESS SECURE APP** option.  
when i fillup this signup page i get these emails right away.

![image](https://user-images.githubusercontent.com/89451747/145754737-9273bfdd-0164-44c0-8ca2-6d16247895df.png)  

Which shows that email confirmation is doing well with this app797644@gmail.com. But not working when i implement this same in your project.

**Comment by egorsmkv** [comment]
Please, check out configuration again

Maybe, you missed something
