### ISSUE TITLE
Update in code corrupted the session data?

### ISSUE THREAD

**Issue by I-am-vishalmaurya** [egorsmkv/simple-django-login-and-register#98]
Thanks for such awesome templates It make my life so easy. I had one doubt that every time I update source code the session data is deleted, and I have to login again to make it work. But is there any way so that session data does not get corrupted in Debug mode?

**Comment by egorsmkv** [comment]
maybe to check "remember me"?

**Comment by I-am-vishalmaurya** [comment]
No its not working even after checking remember me.

**Comment by I-am-vishalmaurya** [comment]
https://github.com/I-am-vishalmaurya/django-authentication-template

Here is the code I have just modified the layout on the pages

**Comment by I-am-vishalmaurya** [comment]
Could these be related to Django version currently I am using 2.2.27?

**Comment by egorsmkv** [comment]
Why did you remove the LICENSE file?

**Comment by I-am-vishalmaurya** [comment]
> Why did you remove the LICENSE file?

Is LICENSE file necessary? If you want I can add it.

**Comment by egorsmkv** [comment]
> > Why did you remove the LICENSE file?
> 
> Is LICENSE file necessary? If you want I can add it.

Of course it's necessary and you should read its content

**Comment by I-am-vishalmaurya** [comment]
Sorry i am still not familiar with the LICENCE on GitHub I thought they were some text. 
By the way I have added the LICENCE.
